Dojo/a very big sum
training-center/dojos pull request #4
Opened 2017-11-26 14:45 UTC by adrianoavelino

Código gerado durante o dojo do dia 25/11/2017 utilizando a linguagem PHP utilizando o desafio do [HackerRank](https://www.hackerrank.com/challenges/a-very-big-sum/problem)

2017-11-26 15:26 UTC, lflimeira requested changes
@adrianoavelino , faltou aquela parte de pontos positivos e negativos e o que foi aprendido no dojo. Pode adicionar isso pf? 😃

2017-11-26 15:39 UTC, adrianoavelino commented
Então, na verdade o desafio nem foi concluído. O Maicon combinou algo de terminar outro dia. Acho que temos que definir isso com o pessoal que particiou

2017-11-26 20:39 UTC, lflimeira commented
Entendo @adrianoavelino, mas o Dojo n precisa terminar. Lembra na semana passada que fizemos mesmo sem o Dojo acabar e colocamos como status: incompleto. Dessa forma outras pessoas podem tentar terminar depois. 😃

2017-12-02 13:16 UTC, adrianoavelino commented
Adicionado um README dentro do desafio

2017-12-21 11:23 UTC, woliveiras commented
@lflimeira tudo ok aqui, meu querido?

2017-12-26 13:24 UTC, lflimeira approved these changes
Tudo certo @woliveiras, desculpa a demora.

Obrigado pelas alterações @adrianoavelino =)

2017-12-26 13:40 UTC, merged